services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ml-jupyter

    ports:
      - "8890:8888"

    volumes:
      - .:/home/smith/work

    working_dir: /home/smith/work

    restart: unless-stopped

    command: >
      start-notebook.sh
      --ServerApp.token=''
      --ServerApp.password=''
      --ServerApp.allow_origin='*'